### ISSUE TITLE
Which socket is which?

### ISSUE THREAD

**Issue by arpheno** [johanahlqvist/poe-timeless-jewel-multitool#11]
Thank you for making this awesome tool.

I got it running for mod search locally and I also found jewels that do what i want them to do.

What i struggle to figure out is which socket_num is which? How do i know what socket_5 means?

Thank you again.

**Comment by johanahlqvist** [comment]
Hi, glad you like it!

As there is no convention on the naming scheme of the sockets (at least as I know of), I just indexed them from the inside out in a spiral, i.e. in the same order that the bot records them. An image giving each socket number's rough position in the skill tree should be available in the top left corner of the search tool. In case it isn't there, I attach an image of it. 

![socket img](https://imgur.com/RwQtTz2.png)

Currently there's no selector for socket_id in the search tool either, so you'll have to ctrl+f the socket id you're interested in once you've got the grip of the naming scheme.

**Comment by arpheno** [comment]
of course... how could i not see this.

**Comment by arpheno** [comment]
will you take prs from me? i will add a bunch of functions for myself i think...

**Comment by johanahlqvist** [comment]
> will you take prs from me? i will add a bunch of functions for myself i think...

Definitely, PRs would be very appreciated!
